heat_template_version: 2014-10-16

parameters:
  ComputeKernelArgs:
    description: >
      Space seprated list of Kernel args to be update to grub.
      The given args will be appended to existing args of GRUB_CMDLINE_LINUX in file /etc/default/grub
      Example: "intel_iommu=on default_hugepagesz=1GB hugepagesz=1G hugepages=1"
    type: string
    default: ""
  ComputeHostnameFormat:
    type: string
    default: ""

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: compute_kernel_args}
      - config: {get_resource: wipe_disk}
  compute_kernel_args:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/bin/bash
        sed -i -e "6d" /etc/default/grub
        sed -i -e '6i GRUB_CMDLINE_LINUX="console=tty0 console=ttyS0,115200n8 crashkernel=auto rhgb quiet intel_iommu=on pci=realloc"' /etc/default/grub
        grub2-mkconfig -o /etc/grub2.cfg

  wipe_disk:
    type: OS::Heat::SoftwareConfig
    properties:
      config: {get_file: /home/stack/templates/sriov/wipe-disk.sh}

outputs:
  OS::stack_id:
    value: {get_resource: userdata}
