resource_registry:
  OS::TripleO::Compute_1::Net::SoftwareConfig: /home/stack/nic-configs/compute_1.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/nic-configs/controller.yaml
  OS::TripleO::Compute_2::Net::SoftwareConfig: /home/stack/nic-configs/compute_2.yaml  
 
parameter_defaults:
  ExternalNetCidr: '10.11.48.0/24'
  ExternalAllocationPools: [{'start': '10.11.48.181', 'end': '10.11.48.190'}]
  ExternalNetworkVlanID: 10
  ExternalInterfaceDefaultRoute: '10.11.48.254'
  InternalApiNetCidr: '192.168.124.0/24'
  TenantNetCidr: '192.168.123.0/24'
  StorageNetCidr: '192.168.125.0/24'
  StorageMgmtNetCidr: '192.168.128.0/24'
  InternalApiAllocationPools: [{'start': '192.168.124.20', 'end': '192.168.124.200'}]
  TenantAllocationPools: [{'start': '192.168.123.20', 'end': '192.168.123.200'}]
  StorageAllocationPools: [{'start': '192.168.125.20', 'end': '192.168.125.200'}]
  StorageMgmtAllocationPools: [{'start': '192.168.128.30', 'end': '192.168.128.60'}]
  # Leave room for floating IPs in the External allocation pool
  InternalApiNetworkVlanID: 30
  StorageNetworkVlanID: 20
  StorageMgmtNetworkVlanID: 40
  TenantNetworkVlanID: 50
  ControlPlaneDefaultRoute: 192.0.2.1
  EC2MetadataIp: 192.0.2.1
  NeutronExternalNetworkBridge: "''"
  ControllerCount: 1
  #ComputeCount: 0
  Compute_1: 1
  Compute_2: 1
  ControllerSchedulerHints:
    'capabilities:profile': 'control'
  Compute_1SchedulerHints:
    'capabilities:profile': 'compute_1'
  Compute_2SchedulerHints:
    'capabilities:profile': 'compute_2'
